color: null
description: null
fieldLayouts:
  1da23a26-767d-424c-a8c3-4a79d999e176:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-16T04:35:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56ba16c7-f70c-462a-8f31-765bc07d9115
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:38:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2f60d8-d811-462d-9df2-c97feb084a2c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a093b7b5-f8db-44bd-83e0-acbc8c112a5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5440782c-41bd-45a7-9d2d-c79a4652b91c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b7f4a41-dc09-41ae-9623-e056c630f017
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a8d101d5-922b-4075-bf81-682426a945a4 # Paragraph Left Aligned Body Text2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c199dcf5-b017-426f-aa0f-a35c779b0cbc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d760ba30-262b-46c3-8e86-b06b07b0226a # Paragraph Right Aligned Image2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57c4541b-fead-4ddc-82be-689387e8b7c8
            userCondition: null
            warning: null
            width: 100
        name: '360 approach'
        uid: 6337cc5f-bcc6-4bde-92c4-8609947ded9d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e10281d4-9a9b-44bb-bd43-1dadbd1514a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 40d419f5-cb74-4388-a019-2ac901bf2ba4 # Paragraph Right Aligned Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5ecb6ac-4b9c-4752-b628-e0b28f7dd5c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:52:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4f6c8e0b-055b-4db8-a5da-6e57516a5d6e # Paragraph Left Aligned Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6b6b3d6-5f8f-4fe5-9641-b81515c80b85
            userCondition: null
            warning: null
            width: 100
        name: 'Finances are personal'
        uid: f04ae715-e395-405f-a44e-88a132a01c72
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-16T04:54:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62fe83ad-50c0-4471-99c5-5809efee9295
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:54:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a8d101d5-922b-4075-bf81-682426a945a4 # Paragraph Left Aligned Body Text2
            handle: paragraphLeftAlignedBodyText22
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aebaa5a0-686e-4370-85a7-00cecc342491
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-16T04:54:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d760ba30-262b-46c3-8e86-b06b07b0226a # Paragraph Right Aligned Image2
            handle: paragraphRightAlignedImage22
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd0d2f44-cfcc-44bf-8f67-eb70de4e9e39
            userCondition: null
            warning: null
            width: 100
        name: 'Passing on our knowledge'
        uid: f3770b49-1933-4386-ad51-511c353d8450
        userCondition: null
handle: about
hasTitleField: true
icon: null
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
