allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  7d40b725-9917-4b68-ab52-9a677d7bda0b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-17T03:44:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9eb27c7-e826-43d5-9470-8610acc69bc0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-04T03:03:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed85ed2c-7145-45ce-9565-a2d0ce2dd9d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:53:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec495c41-be88-425f-a0d4-aff963125c1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:53:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0f18605-0220-44cc-9ba1-aee77374199d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7856aa9-d4e1-47c6-8799-09343b622495
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-17T03:53:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbd6e0a3-ab17-47e4-9f14-19dc482e6992
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T20:38:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b3d02c0f-4eb6-471b-a4fd-e7ade89de423 # Hero Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 347b71e8-c18b-44ac-9ca1-4996697a2d66
            userCondition: null
            warning: null
            width: 100
        name: 'Accounting for better business'
        uid: 67c42a61-2d65-4f1d-8b5c-ef32eeb6b3ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-08T21:15:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 489aa9de-78dd-4788-80c7-9307d470bb57 # Main Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8806e64d-523d-45ce-9a1f-af381d69f8ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T20:38:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3d80242-c271-4622-992f-092daa2eb937
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T21:15:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18413b7d-861a-4785-ad1c-17abd295838e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T20:51:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c8cb479b-6ce3-44d4-8485-2de5b6cff170 # Accounting Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d321afc-4033-42fe-9c7e-dbe2f5ba1226
            userCondition: null
            warning: null
            width: 100
        name: 'Accounting to keep things humming'
        uid: 56b1bd0b-b6e9-4d76-9b12-bd2200a6e95d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-08T21:15:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 473c4361-ce0b-4af3-8c12-f422981b0587
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T21:15:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87a5b381-9e3b-43fe-a9dd-a55d53196b07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T21:15:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b527412-a4d6-42ae-bb49-7c55af321db7 # Accounting table
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cd9de2f-4c0e-42b0-be71-9e2ff7f6c2da
            userCondition: null
            warning: null
            width: 100
        name: 'Our 8 critical pathways for success'
        uid: d3dd6c71-7039-4e5b-94a2-fccc1c16864e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-08T21:52:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89bdcc47-51cf-4eaa-8389-0405f52fd0aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T21:52:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb459c2e-3c79-46b3-95de-6f9b4cebae59
            userCondition: null
            warning: null
            width: 100
        name: 'How we work with you'
        uid: 8fd46959-b147-4307-8a57-6aa4541dc1f8
        userCondition: null
    thumbFieldKey: null
handle: accounting
hasTitleField: true
icon: null
name: Accounting
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
