color: null
description: null
fieldLayouts:
  72456d5c-851f-46d9-af13-d17a42dd8d94:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-17T03:42:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4945faf0-24b3-4c9d-b959-4cba81b7e5a0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7f5c4aa-3b69-4696-9ec9-422d866dee6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86e8834d-bbd3-4619-af66-58e641942c21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T02:27:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ca03538-edb7-4628-8612-0b48a9cd0da5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T02:24:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be3cd0d1-7caf-4e70-a264-6c21d71840ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc4ff1cc-860b-4efa-a7a4-aad181294b2d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-17T03:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 595046b3-e807-4657-9ce0-3588a5720dea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86ec663c-3172-452e-9c31-5fed9d5e0de0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 068ece1a-2225-48af-88e8-aa15e391ef18
            userCondition: null
            warning: null
            width: 100
        name: 'Guidance for building your business'
        uid: be44269a-61a4-4aad-b335-19347c931e18
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T02:33:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bda1f66-e18c-45b5-8dd1-152f3d311202
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T02:27:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0adb35fa-bbdf-4081-b264-46b11d92fe55
            userCondition: null
            warning: null
            width: 100
        name: 'Explore Business Services'
        uid: d8ca2d27-6a54-4301-b075-114ef7ab6935
        userCondition: null
      -
        elementCondition: null
        name: 'Who we work with'
        uid: 51686398-a9b4-4fab-b91e-591f7a2e9384
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T02:18:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d75d6e-8350-4957-b19c-6e2635b74f6f
            userCondition: null
            warning: null
            width: 100
        name: Testimonial
        uid: 89486b09-5f18-4db2-bf4a-001605b83a3b
        userCondition: null
handle: businessPage
hasTitleField: true
icon: null
name: 'Business Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
