allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  01df7131-62fb-4dc7-bed8-c2ffa3ebccaa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-29T01:46:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 26b9329d-ceec-42d9-8325-88d50abb8660
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:53:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02ee8b54-f5bc-498d-96da-95b1718c7c78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:53:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b03f904-e25f-420d-93c3-03f449426beb
            userCondition: null
            warning: null
            width: 100
        name: 'Careers '
        uid: 8f4b4d9b-7402-4d55-a4ad-2c9e13946013
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T02:05:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6a8f4236-25e3-4199-b476-1f7eddcf04cf # prehead
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae78749-5a66-4f90-9f33-ee51d2fdb6fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T02:05:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4c9973ff-0107-4739-a889-f352e62eca08 # Large Paragraph
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ab19182-0900-42bf-9279-a838bb229c15
            userCondition: null
            warning: null
            width: 100
        name: 'Foxplan Academy'
        uid: e9fe0edf-7f98-4281-b90a-064081ffc974
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T02:16:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0535f582-c6a4-492c-8a70-1b34948f8721
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T02:16:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 228afc8d-184c-4f9b-8dcc-b667d81e28d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T02:42:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3df564bb-a8ff-48d9-88c0-1e1fec7a3cff # Accordion new
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8816e65-a029-4971-9951-7cd17f4ccc24
            userCondition: null
            warning: null
            width: 100
        name: 'Current Oppurtunities'
        uid: 7719d641-354e-4e3a-ae5c-4fe0c8854136
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T23:13:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e448283c-7112-4340-9be7-7ee8155d95a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:13:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40ea77bd-e781-4db7-b66a-2da90a9009ab
            userCondition: null
            warning: null
            width: 100
        name: 'Benefits and Features of a Career At FoxPlan'
        uid: 9c5c0194-fcd4-4580-9aaa-b0120f7a6adf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 489aa9de-78dd-4788-80c7-9307d470bb57 # Main Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 866a6f4f-4b24-4973-8ff6-1e6880a9f50c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76d40e60-1aea-4385-a068-e72ef85be118
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 48d413cb-263e-48f8-976a-5aecadda1537 # Short term matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21aa6bf7-74b5-45cf-b54b-40d46457633a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-10T01:42:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30be4b0d-0cb1-485b-818a-09f565dabaa0
            userCondition: null
            warning: null
            width: 100
        name: 'The Short Term: Foundation & Integration '
        uid: 8eb60236-a9ce-409a-9b7e-8f2a13981cbd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 489aa9de-78dd-4788-80c7-9307d470bb57 # Main Title
            handle: mainTitle2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c1d634b-17e7-42a2-a050-c7e5820b136a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e5808b9-730c-4ad0-9c9d-923985efa80d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:19:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ec05ea4a-53c2-41fa-a6c1-1b42827ace64 # MediumÂ Term matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e65984ed-79b4-4f5c-8b16-5332159cf050
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-10T01:42:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: image2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1b5c9f1-b9bf-4e76-a320-e6cdc740e486
            userCondition: null
            warning: null
            width: 100
        name: 'The Medium Term: Growth & Practice Mastery'
        uid: 77acdd23-b550-42d1-a477-af1f2f04636e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 489aa9de-78dd-4788-80c7-9307d470bb57 # Main Title
            handle: mainTitle3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 710d0283-b00d-4fd9-be12-658a586cbc7f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:18:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55405864-bab8-48b6-8e72-14b93148f815
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:19:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f86d97d1-d318-4c48-96df-cbcb0d340f78 # Long Term matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2bb5cf5-5bf6-41d9-97ce-b27e5801ec77
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-10T01:42:56+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: image3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6216a06-f57a-43ae-a124-c3f67180b24a
            userCondition: null
            warning: null
            width: 100
        name: 'The Long Term: Ownership & Exit'
        uid: 6ffccb4a-9e2a-4f75-b6e0-b175bc8c3267
        userCondition: null
    thumbFieldKey: null
handle: careersPage
hasTitleField: true
icon: null
name: 'Careers Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
