allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  53d1c460-a894-45d3-b5f7-e6d06e5cef90:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T23:16:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 96c1e443-01b6-463e-b149-11a8187fafae # Matrix Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de5dab0c-6db5-4f0a-af85-e59997923cba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T23:16:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f76d141-ff1e-4649-9dce-06c7a60137be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8eed0698-f3f5-45bf-8d7f-acb43d1df647
        userCondition: null
    thumbFieldKey: null
handle: careerBenefitMatrix
hasTitleField: false
icon: null
name: 'Career Benefit matrix'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
