allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  01df7131-62fb-4dc7-bed8-c2ffa3ebccaa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-29T01:46:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 26b9329d-ceec-42d9-8325-88d50abb8660
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:53:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02ee8b54-f5bc-498d-96da-95b1718c7c78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:53:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b03f904-e25f-420d-93c3-03f449426beb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f4b4d9b-7402-4d55-a4ad-2c9e13946013
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T02:05:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6a8f4236-25e3-4199-b476-1f7eddcf04cf # prehead
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae78749-5a66-4f90-9f33-ee51d2fdb6fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T02:05:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4c9973ff-0107-4739-a889-f352e62eca08 # Large Paragraph
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ab19182-0900-42bf-9279-a838bb229c15
            userCondition: null
            warning: null
            width: 100
        name: 'Foxplan Academy'
        uid: e9fe0edf-7f98-4281-b90a-064081ffc974
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T02:16:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0535f582-c6a4-492c-8a70-1b34948f8721
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T02:16:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 228afc8d-184c-4f9b-8dcc-b667d81e28d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T02:16:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c160e9df-1b1b-4b66-a3d1-7ea0a1c6be39
            userCondition: null
            warning: null
            width: 100
        name: 'Current Oppurtunities'
        uid: 7719d641-354e-4e3a-ae5c-4fe0c8854136
        userCondition: null
    thumbFieldKey: null
handle: careersPage
hasTitleField: true
icon: null
name: 'Careers Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
