allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8287ce2a-030c-43a0-97c8-b497af07a6b2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-16T03:28:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Client Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8fb38d08-db89-47bf-8d1b-adcb0445cf0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-16T03:30:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 850eeb95-fac6-4d9c-a93f-eb8e4939ca9a # blockBodyText
            handle: null
            instructions: null
            label: Testimony
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f780dd0-9363-4a8e-b996-204d5c168551
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b9fe4f4-ecfb-4134-82ff-968729cd5bad
        userCondition: null
    thumbFieldKey: null
handle: clientTestimonial
hasTitleField: true
icon: null
name: 'Client Testimonial'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
