allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  2675129c-8a99-490a-ba27-665dc5c0657f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-26T01:59:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 331970c8-e670-403b-8550-b3a3214d6a62 # Member Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd624c49-5bfb-45b5-834f-ed2bfa436adb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-26T01:59:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c8cad64-726d-4735-be40-5f733d49e15b # Member image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea26f14b-6575-442a-9c65-6a96e704a80d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-26T01:59:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 33a1b6df-526d-4d3c-84a1-dcc713555b4d # Job Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1b3cd33-b543-4f57-a1ad-07fa4912c8db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-26T02:11:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98ed4338-368d-4c6d-b720-bcafdffae1b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c83ea312-343e-4ba4-8033-b258cfea4797
        userCondition: null
    thumbFieldKey: null
handle: committeeMembers
hasTitleField: false
icon: null
name: 'Committee Members'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{memberName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
