allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  4b187f44-f932-4098-a5ab-afdf794767cc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-28T00:26:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 366ff6f0-3e60-415d-b926-396a17ffef21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9717edfc-9a94-42c7-a1fb-1ddc343b2572
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad3bba39-aec4-463f-8755-9d98eb80f836
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Us'
        uid: 57ee0607-18af-4a4e-becf-d5eca93dcab6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 85b764d9-d1dd-4aad-9cfb-e7432652aad7 # Contact Main Heading
            handle: contactMainHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7766e2cd-295d-4fa4-b528-0c0214e987c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7f147ed-33aa-4d4a-bf02-bbebd30804fe # Contact Bodytext
            handle: contactBodytext2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d0dca0-dd3e-47b3-919d-9a72a1fb259b
            userCondition: null
            warning: null
            width: 100
        name: 'Get in touch'
        uid: 02186849-e7d2-49cb-becc-93d2a1610a73
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 85b764d9-d1dd-4aad-9cfb-e7432652aad7 # Contact Main Heading
            handle: contactMainHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90f5818a-cf44-4a29-b409-04e8900db261
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7f147ed-33aa-4d4a-bf02-bbebd30804fe # Contact Bodytext
            handle: contactBodytext3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 715a1133-030e-4c01-a687-506cb0500319
            userCondition: null
            warning: null
            width: 100
        name: 'Book an adviser'
        uid: 94e2bc7e-d4d7-472a-bc33-c98842d90f4d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 85b764d9-d1dd-4aad-9cfb-e7432652aad7 # Contact Main Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a02744e-2c2f-4ea0-b5a1-307bce9001e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T01:09:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7f147ed-33aa-4d4a-bf02-bbebd30804fe # Contact Bodytext
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 829c288d-d7f4-4805-a51f-444740aa2fda
            userCondition: null
            warning: null
            width: 100
        name: Location
        uid: 502c876a-a80f-40f3-91e5-e70d24d263cf
        userCondition: null
    thumbFieldKey: null
handle: contactUsPage
hasTitleField: true
icon: null
name: 'Contact Us Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
