color: null
description: null
fieldLayouts:
  4b187f44-f932-4098-a5ab-afdf794767cc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-28T00:26:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 366ff6f0-3e60-415d-b926-396a17ffef21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9717edfc-9a94-42c7-a1fb-1ddc343b2572
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad3bba39-aec4-463f-8755-9d98eb80f836
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb8f7b78-4b07-4b23-8128-0e5464bb09d3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:26:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc732d40-5b7e-4369-bb83-fcc0da40e76d
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Us'
        uid: 57ee0607-18af-4a4e-becf-d5eca93dcab6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-28T00:59:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1757a17e-5538-4de5-9ff7-fa4d80af64a1 # Location Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46a433ed-0a7d-44b1-8e5b-afaed72caa6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-28T00:59:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3596a73-fe19-4305-93f4-0d508c177dbc # Location Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d8b58a8-a515-4531-8e47-a95e5abff850
            userCondition: null
            warning: null
            width: 100
        name: Location
        uid: 502c876a-a80f-40f3-91e5-e70d24d263cf
        userCondition: null
handle: contactUsPage
hasTitleField: true
icon: null
name: 'Contact Us Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
