allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0fcd128f-b5ad-4b94-89e3-0b7dbbd54825:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-02T01:00:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 60614e67-d787-46ca-8229-8a163deb7064 # Heading Line1
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53e47120-e76e-4128-a782-c57162f14a7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-02T01:00:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f1c902fb-3573-4fe5-872f-68ef7fe938e5 # Heading Line2
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9831fd94-40c9-4467-a6fa-4d409f806fcb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T20:37:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a88d2a6b-57ef-4871-bdcc-33c29f573e95
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T20:37:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07e69a33-c83c-425b-96ef-4847f7e28d54
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-04T03:59:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d85115-88bd-4d52-8876-ca35db09600c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9463889a-52f1-4671-b3db-08f6019d522e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-01T21:37:11+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3f6621b-76e1-48bc-ad79-d612a3e94da3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T21:37:11+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b8cb4ee-abde-43b5-b7bb-b7608c0eb8cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T21:37:11+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b3d02c0f-4eb6-471b-a4fd-e7ade89de423 # Hero Matrix
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0830832-5d3f-48ec-8809-756916141f30
            userCondition: null
            warning: null
            width: 100
        name: "30 years of working \ntogether"
        uid: 916f3662-453d-4d5e-a266-10cfb27778f8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-01T22:16:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4d12b2-c71d-47c1-8ad6-b775f9ff2367
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T22:16:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f060599-8962-42c7-8469-abbe0fc3a3ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T22:15:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 98874d4e-7f67-4c96-8e6a-1ae5b6fc4961 # Services
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c929731-c5c9-4ad4-a70c-51b530465118
            userCondition: null
            warning: null
            width: 100
        name: Services
        uid: a40f40be-d56f-4b23-a315-cd0f37fd5a5d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-01T22:58:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e085ad53-994b-4dba-9638-e6c453d53d59
            userCondition: null
            warning: null
            width: 100
        name: Testimonials
        uid: 26bdd69a-9aaa-45cb-84c3-ecaf970aedf4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-01T23:13:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 527d4f3b-96d6-4b3e-b207-73b27e120700
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:13:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ab0cfd3-bbe0-4243-a9fc-7afe521ad8e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:14:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: button2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3c4aa20-5b1c-4edf-bb0e-553b5e2fc466
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:21:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 703fea39-0a89-4b7d-93b4-9982b3cc9ecf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T22:23:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c99b49ab-de71-4f47-99b4-166cfc93b301
            userCondition: null
            warning: null
            width: 100
        name: 'Where should I begin'
        uid: 4820e4e0-d6f9-4a18-8514-cadef4393db8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-01T23:13:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 111a20b3-7acc-4f3a-907d-0e46e366b180
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:13:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da49211f-f51f-4d2a-ab36-a8343bd12ba0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:14:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: button3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 690c51d5-4d39-4965-bb67-4662d77e4046
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-01T23:21:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: buttonLink2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db18234d-ba86-4d4c-9337-97a30e508c2f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-08T22:23:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: image2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1a183fa-cf74-4a80-9537-43b8d761c5d0
            userCondition: null
            warning: null
            width: 100
        name: 'Subscribe to Dollars and Sense Podcast'
        uid: 6b291377-d702-43e8-8dcf-6948edaf0af6
        userCondition: null
    thumbFieldKey: null
handle: home
hasTitleField: false
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
