allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  de7e6c3e-2374-4ad1-81e2-5f70b7a42683:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-15T21:58:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 024975a0-c902-455c-8531-31c3d872cb09 # blockHeading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0d8ed08-0484-4a74-91ad-439deeeba8be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T21:58:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 850eeb95-fac6-4d9c-a93f-eb8e4939ca9a # blockBodyText
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29015ccc-d079-477b-84ee-8cc8db2b6312
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T21:58:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5a33ed06-c4f0-4d32-be5f-033502c710e5 # blockLinkUrl
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e9f8166-1008-4c76-9f4d-0f53a2491230
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4bd01650-002b-4ad7-ba98-61902d76e9db
        userCondition: null
    thumbFieldKey: null
handle: infoBlock
hasTitleField: false
icon: null
name: 'Info Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
