allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  6e287d58-a3e9-441c-88a6-10668cf3f4c1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-17T02:17:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ae1eb8ab-68f8-419c-8bb8-c19ed7985884 # Insights Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 084c5e1c-2381-46f3-bef2-26e91c7f38cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T02:17:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e4ad5282-5b53-4193-bf9a-40d21e1aab4d # Date
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 651165a9-248b-4843-b8b2-bb26434e1104
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T02:17:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4a5c0332-8175-4c2d-b8c5-0e1602083956 # Insights Heading 
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aee65259-737c-41df-ae77-a16a5acb73a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T02:17:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d2ec8d-ae87-4dab-8c8e-67abe9844f9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T02:11:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a82e8874-a0f4-4805-b59d-8c47d4867d7c # Tags
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a19c3cf-52df-45aa-a107-687521e5c65d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d118a6b-d2d6-49fd-9a68-5688fdae6426
        userCondition: null
    thumbFieldKey: null
handle: insights
hasTitleField: false
icon: null
name: Insights
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
