color: null
description: null
fieldLayouts:
  9a769fbb-6e9b-4ab4-ac12-5c8423d3eccd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T01:33:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c8cad64-726d-4735-be40-5f733d49e15b # Member image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a4fab86-299c-403b-b549-c49bf34ab7a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T01:33:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 331970c8-e670-403b-8550-b3a3214d6a62 # Member Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e34f86-1d8e-4fdc-9c32-c68397e53dab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T01:32:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 33a1b6df-526d-4d3c-84a1-dcc713555b4d # Job Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c107dbf-e05f-43fe-8019-16f80648ffe9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T01:32:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee8d1ad8-d53a-4a53-b1d0-ba3e280a9cb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T01:32:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 73262043-6292-4645-96a8-99ed862cd739 # Phone Number
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80e2bd6d-6132-42b5-b86b-8d31931bf264
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T01:32:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f41f4500-6b84-466c-89f3-dae1d5c3bf36 # Category
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbafe904-77e5-4bb7-a0d7-2b808190fe6a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65e85ad3-372c-4da7-8d5b-1b7b4c8c178d
        userCondition: null
handle: meetTheTeam
hasTitleField: false
icon: null
name: 'Meet the Team'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{memberName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
