allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f1cfbcaf-8f69-4257-8478-7175856242cd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-17T03:31:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4f329d97-d314-41c5-8694-9245b1747f47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:36:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8da058c6-5497-4d60-b363-86a7ab1bcfce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:36:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aecc1104-e4b1-4ac6-8763-e8600a501a76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-04T04:25:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 088fdc97-0782-48cb-a226-78cca1e561b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6cae508-f1eb-44e4-8064-162eded98482
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-17T03:36:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fafe2f5d-7e10-4296-b2d9-07f14d530a03
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:36:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99cc9f7a-0640-4662-bb80-1b2347e7416d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:36:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecf5b913-a3f2-4dec-bef4-59d0e8eb3120
            userCondition: null
            warning: null
            width: 100
        name: 'How your Adviser can help  '
        uid: 4f0227b9-d5e7-492a-82e3-f05173faaa89
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T21:47:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12ddb483-6330-449f-ae88-f74cdea2b1e4
            userCondition: null
            warning: null
            width: 100
        name: 'Explore Mortgages'
        uid: ed0c01e6-74c4-4ecf-9bcf-353eb3b319fc
        userCondition: null
    thumbFieldKey: null
handle: mortgages
hasTitleField: true
icon: null
name: Mortgages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
