color: null
description: null
fieldLayouts:
  58a678a3-66ff-4b75-8778-73626bca2f7b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-26T02:20:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41a05438-d973-47d3-ad06-745e2b36a715
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-26T02:55:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48388d67-341e-4c37-bb68-56c92972b645
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-26T02:55:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fb71e28-361c-4e11-af8e-c0376af4cfd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9052fb83-cf55-4256-b86d-9947c8dc80f0
        userCondition: null
handle: ourInvestmentCommittee
hasTitleField: false
icon: null
name: Our-Investment-Committee
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
