color: null
description: null
fieldLayouts:
  76350750-c7ee-43e0-945a-a804dc1dd5b6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-25T21:01:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b974ddd6-5e6a-460f-8100-45bdf6fe5c1d # Provider Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22b211bc-3e60-4057-adf6-1bda3e1589de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-25T21:01:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30e93460-18e1-473b-90f6-17bed59eb35e # Contact Info
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d599bff-0b71-44f0-8dd2-db9d957b09e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T01:07:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 544d4692-c910-412c-97e7-77d0fc357686 # Suppliers Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8664fb2c-446a-43c0-9912-61225c863bcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T01:07:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcf9c894-6cf3-4033-af0b-b5c5df178c8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-25T21:01:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccded4b2-e534-4bba-9688-f53daa4e83ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-25T21:01:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 50a671c8-233b-479c-af1a-8dfcc5f25e8f # Supplier category
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 459515b8-fbda-45a1-a2ef-8d3f7042fee1
            userCondition: null
            warning: null
            width: 100
        name: Suppliers
        uid: 5c994281-91e6-4edc-9148-29e8bb6da1e3
        userCondition: null
handle: ourSuppliers
hasTitleField: false
icon: null
name: 'Our Suppliers'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{providerName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
