color: null
description: null
fieldLayouts:
  e2c8a9ac-4ba7-45c4-80f9-24437f4aa31b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-15T22:24:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67381afc-8a7d-40e2-9e37-3707f6fad626
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f49202e4-9132-4105-a416-0d4d132d991b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa510f0b-2e61-4b87-a123-bb249aa0b9b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d278e4dd-44dd-44e5-88cd-a60421a01426
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 282cfa4c-531f-49d7-862c-d493d895351c
            userCondition: null
            warning: null
            width: 100
        name: hero
        uid: 12842580-8fbd-49c9-8221-94f09cafeb5a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T22:25:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4db47a3b-af93-4561-be60-cc9725abb8c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1f6f062-a349-4686-a0f3-e98071c1a576
            userCondition: null
            warning: null
            width: 100
        name: 'Info Block'
        uid: 9bd63c52-b0c8-4c43-9908-39e312c3c689
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T23:19:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80856add-51d5-4af1-8a8a-4c727fc3cceb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c131603a-f023-4fc8-a709-18ff54603eb0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 423f046c-e3a3-405f-94f6-f79e72ce757e
            userCondition: null
            warning: null
            width: 100
        name: 'Accordion Section'
        uid: 803a2ba5-2588-4d98-b6e8-695427d9d11f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13c42c3f-123c-4eb1-acfe-b7193aead55f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56c77830-38a8-4104-8cac-afb83c4a4c99
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee2b36bd-ec01-4975-b25d-8891e9fbebb5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:53:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: button2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e4a59e1-a856-4211-ad2e-f324ec465701
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:53:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: buttonlink2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 775ca670-b6ee-44ff-90dc-ef1157c94b6a
            userCondition: null
            warning: null
            width: 100
        name: 'Image and text'
        uid: 7d38c113-0252-45ee-bdf6-f0660ca69cc2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-16T03:22:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c6120c8-42f1-40e8-a3a2-d766922ef9d6
            userCondition: null
            warning: null
            width: 100
        name: Testimonials
        uid: 6ac57fca-7c2d-458f-b415-ce20c8257a4c
        userCondition: null
handle: pageBuilder2
hasTitleField: true
icon: null
name: 'Page Builder2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
