allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e2c8a9ac-4ba7-45c4-80f9-24437f4aa31b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-15T22:24:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67381afc-8a7d-40e2-9e37-3707f6fad626
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f49202e4-9132-4105-a416-0d4d132d991b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa510f0b-2e61-4b87-a123-bb249aa0b9b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d278e4dd-44dd-44e5-88cd-a60421a01426
            userCondition: null
            warning: null
            width: 100
        name: hero
        uid: 12842580-8fbd-49c9-8221-94f09cafeb5a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T22:25:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4db47a3b-af93-4561-be60-cc9725abb8c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1f6f062-a349-4686-a0f3-e98071c1a576
            userCondition: null
            warning: null
            width: 100
        name: 'Info Block'
        uid: 9bd63c52-b0c8-4c43-9908-39e312c3c689
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-09T00:00:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9582acd2-85fd-4274-b0f6-373bbc759b41
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-15T22:34:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c131603a-f023-4fc8-a709-18ff54603eb0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T00:40:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe65fafc-55a8-474b-bd0f-a76a970e15a5 # Accordion
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8bbfcd7-08ca-42e5-869d-d1eb313e888e
            userCondition: null
            warning: null
            width: 100
        name: 'how we work with you'
        uid: 24bf0b37-3158-4ae9-9b01-83ed34d6dadd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-09T00:45:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a34b755-526e-47a8-800f-67eab152e3d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T00:45:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdc22ce6-fda0-4a6d-96dd-d881ff938568
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T00:45:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: button2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77837a2a-3268-483c-aa3e-97f5f3829400
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T00:45:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8da3467-e2fa-4b90-b5e8-7df257de2ebc # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 674187dd-6caf-423d-b3c8-d54f994e18ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-11T01:00:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a60554c1-42e9-4a93-b213-3950bf23db7d # Button URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25f5f847-556d-4033-b71d-6a5fe4034878
            userCondition: null
            warning: null
            width: 100
        name: 'image and text'
        uid: 60e4381b-2c5b-4f56-bdfa-768e44813df3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-16T03:22:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c6120c8-42f1-40e8-a3a2-d766922ef9d6
            userCondition: null
            warning: null
            width: 100
        name: Testimonials
        uid: 6ac57fca-7c2d-458f-b415-ce20c8257a4c
        userCondition: null
    thumbFieldKey: null
handle: pageBuilder2
hasTitleField: true
icon: null
name: 'Page Builder2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
