allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  70bd36a0-f9c8-4d55-b4f2-c250b13e8474:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-17T03:38:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e57ad7da-c977-4463-a6d0-8b277d7cca94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:42:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba06c181-87ee-4bbd-ac65-6924640190e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:42:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fa6d9e2-b079-4a84-9bc6-a98421339873
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-10T01:00:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e480fc5c-40a5-4c81-8f02-f3442537ffa3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0649c60-f3b9-4754-b77e-871f4947ad20
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-17T03:42:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acbdb752-fe37-49a8-bbdf-8800de5c78c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-17T03:42:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce5ebd85-c25e-4959-9c03-6b82b22ed55e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-09T01:44:04+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3df564bb-a8ff-48d9-88c0-1e1fec7a3cff # Accordion new
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e44050da-24e4-4d28-9211-36aaad03fb15
            userCondition: null
            warning: null
            width: 100
        name: 'Gain Control,Confidence'
        uid: eb0624fe-6358-4a73-b0aa-04ed41d5331a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-21T20:35:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7d60edd-b264-493f-8767-157ddb82d4eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T20:35:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7db9c482-08fc-4f89-be96-c9439c169212
            userCondition: null
            warning: null
            width: 100
        name: 'Explore Savings and Investments'
        uid: cd9ac50a-8c15-4f44-9256-79b59b57f627
        userCondition: null
    thumbFieldKey: null
handle: savingsAndInvestmentPage
hasTitleField: true
icon: null
name: 'Savings and Investment Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
