color: null
description: null
fieldLayouts:
  d077c347-f861-48ff-ad52-1ed26850fe6f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-16T03:09:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01d859f3-0f5b-434d-b064-a75dd6b9f60f # Testimonial
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb47aea9-dbc7-43a8-bcc7-318bbae06c6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-16T03:09:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3ca03225-96ae-4b44-87f2-2f3b0d32d166 # Testimonial Author
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddeecf18-0d75-4fbc-a07d-3d8fc5297f5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3bd33c72-b11c-4592-bce8-26a63c5372cd
        userCondition: null
handle: testimonial
hasTitleField: false
icon: null
name: Testimonial
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
