color: null
description: null
fieldLayouts:
  66894257-acca-47ca-88aa-f929fcf7112a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T23:38:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ceace67-0ae8-4312-9232-ff0dab519776
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-19T23:38:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ae579cff-a9c5-4a21-a182-8dc2ad9da475 # Partner Logos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f54f9739-d49a-424d-967c-913968b5164e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 471dad2c-4037-413c-8b27-df5b7f90f1a1
        userCondition: null
handle: whoWeWorkWith
hasTitleField: false
icon: null
name: 'Who We Work With'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
