altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b8e45bcd-5c21-4a53-af92-955246cd6f5a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T22:05:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d8c4b83b-d627-4289-a4e2-7e41782fd1a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 837ef7e2-cef4-4dd8-a774-4110722d3d36
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: articleImages
name: 'Article Images'
sortOrder: 1
subpath: article-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: article-transforms
