altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b9f17516-5829-4f72-a8fb-478b305d88bb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T23:35:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dcabe4f2-1e54-4753-b929-fd4eb49437bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d414aea8-3bf2-4fad-8de7-aaa11fefd70f
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: heroImages
name: 'Hero Images'
sortOrder: 2
subpath: hero-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: hero-transforms
