altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ffd62be4-752d-4baf-a1a5-cd98b4b35975:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-12T04:26:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3a15b482-d734-4351-b574-efbe2fad5ee1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f3fa6b6-fd01-4fc2-b3db-252687d250e6
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: newsImages
name: 'News Images'
sortOrder: 6
subpath: news-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: news-transforms
