altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  be1d9cfa-bc4f-4e35-afe4-ec44cf2abce2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-13T01:23:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 95b72bf5-93f1-4b08-9db6-0031638bb23f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 221d828d-01aa-4d1f-a6a7-f13e565b1edc
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: newsImages
name: 'News Images'
sortOrder: 6
subpath: news-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: news-transforms
