altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9735bc56-7f0b-41a3-9536-c83ecb131de4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-08T22:22:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2b5c2ecc-91fe-4a5f-8a01-9745e7485b36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0869d00-430b-4ad1-bf74-809de4a0a712
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: siteImages
name: 'Site Images'
sortOrder: 5
subpath: site-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: siteImages-transform
