altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  46382e1d-b90a-4836-97f7-e088bb87518a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-04T00:05:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f1092e4f-b0f1-4637-9736-37ec4d44d1a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 785d1feb-c421-4c5b-9d96-6710814fbc28
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: staffImages
name: 'Staff Images'
sortOrder: 4
subpath: staff-assets
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: staff-transforms
