altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  739a8391-e879-4dfd-a993-bd5851403d8b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-04T00:02:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 21ba7b54-1d74-4b49-bf3d-c498424ee208
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff281ba5-41d7-40d3-8edc-fe7133b6b365
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: supplierslogo
name: 'Suppliers Logo'
sortOrder: 3
subpath: suppliers-logo-assets
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: suppliers-logo-transforms
