columnSuffix: null
handle: category
instructions: null
name: Category
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Accounting & Wealth Management'
        -
          - value
          - accountingWealthManagement
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Financial Advisers'
        -
          - value
          - financialAdvisers
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Head Office Staff'
        -
          - value
          - headOfficeStaff
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
