columnSuffix: null
handle: dropdown
instructions: null
name: Dropdown
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
