columnSuffix: null
handle: subscribeButton
instructions: null
name: 'Subscribe Button'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
