defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 83ab9fed-c6f6-4bc3-868d-78df435d9da2 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/About/index.twig
    uriFormat: about
type: single
