defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 43ae8319-1d1a-467f-a54f-c45fae2a173d # Accounting
handle: accounting
maxAuthors: 1
name: Accounting
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Accounting/index.twig
    uriFormat: accounting
type: single
