defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 624fe030-2a18-4f50-92e6-5f5e4d1b8ca4 # Articles
handle: article
maxAuthors: 1
name: 'Article '
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: articles-data/_entry.twig
    uriFormat: 'articles-data/{slug}'
structure:
  maxLevels: null
  uid: 6a88359a-87ad-4f3e-95a3-1896cec8a694
type: structure
