defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b8dfe219-cd2b-4062-b6c5-2a0b07241d1a # Careers Page
handle: careers
maxAuthors: 1
name: Careers
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Careers/index.twig
    uriFormat: careers
type: single
