defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5e5bb650-f40f-4a0a-b4e2-96821fdaae9a # Committee Members
handle: committeeMembers
maxAuthors: 1
name: 'Committee Members'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Our-Investment-Committee/index.twig
    uriFormat: 'our-investment-committee/{slug}'
structure:
  maxLevels: null
  uid: e0a466ed-452d-4077-ba1a-2050b6a3e704
type: structure
