defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 06624620-5204-452f-a746-b5d70f1641a4 # Contact Us Page
handle: contactUsPage
maxAuthors: 1
name: 'Contact Us Page'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
