defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7f789aad-395d-4a42-a977-413640299ad5 # Dollars and sense Newsletter
handle: dollarsAndSenseNewsletter
maxAuthors: 1
name: 'Dollars and sense Newsletter'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: dollars-and-sense-newsletter/_entry.twig
    uriFormat: 'dollars-and-sense-newsletter/{slug}'
type: channel
