defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 40a75dcf-4e4f-46ec-98ec-9424fc33fa4b # Dollars and Sense Podcast
handle: dollarsAndSensePodcastIndex
maxAuthors: 1
name: 'Dollars and Sense Podcast'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: dollars-and-sense-podcast/_entry.twig
    uriFormat: dollars-and-sense-podcast
type: single
