defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ecf3a398-13d9-4319-a852-69760e9374a9 # financial wellbeing page
handle: employeeFinancialWellbeing
maxAuthors: 1
name: 'Employee financial wellbeing'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Employee-financial-wellbeing/index.twig
    uriFormat: employee-financial-wellbeing
type: single
