defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9695c5c9-997b-4776-9806-6bd6bc3478ea # Episodes
handle: episodes
maxAuthors: 1
name: Episodes
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: episodes/_entry.twig
    uriFormat: 'episodes/{slug}'
type: channel
