defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c91c8b47-5983-4466-94b4-44c6cce8e323 # Financial Planning
handle: financialPlanning
maxAuthors: 1
name: 'Financial Planning'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Financial-planning/index.twig
    uriFormat: financial-planning
type: single
