defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3cd32da9-06b0-44c6-a0a8-54568bfbb9b3 # Group-workplace-insurance
handle: groupWorkplaceInsurance
maxAuthors: 1
name: Group-workplace-insurance
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Group-workplace-insurance/index.twig
    uriFormat: group-workplace-insurance
type: single
