defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cc0e715a-9227-4f6e-9948-2b6b82ab16c3 # Insights
handle: insights
maxAuthors: 1
name: Insights
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
