defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1692277e-675a-4ebf-8998-6eb58cf9709f # Insurance
handle: insurance
maxAuthors: 1
name: Insurance
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Insurance/index.twig
    uriFormat: Insurance
type: single
