defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 37d0dcee-fda6-44fc-b96c-3eb521cdaa34 # Join The Team 
handle: joinTheTeam
maxAuthors: 1
name: 'Join The Team'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: join-the-team/_entry.twig
    uriFormat: join-the-team
type: single
