defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: db3f4be3-1c80-405f-840c-01dddd834e4f # Meet the Team
handle: meetTheTeam
maxAuthors: 1
name: 'Meet the team'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: meet-the-team/_entry.twig
    uriFormat: 'meet-the-team/{slug}'
structure:
  maxLevels: null
  uid: 5f861501-79f1-4360-bc41-b01f9063b34f
type: structure
