defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 184304c2-0776-48be-b918-b0c1ec2dc0ee # Mortages
handle: mortgagesPage
maxAuthors: 1
name: 'Mortgages Page'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Mortgage/index
    uriFormat: pages/mortgage
type: single
