defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 442aaa5f-2531-4a40-a133-1b9bcbd25b08 # Our Suppliers
handle: ourSuppliers
maxAuthors: 1
name: 'Our Suppliers'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 10be98bd-7b1c-4dfd-8f60-3129f80a5448
type: structure
