defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ab6e0b50-c8e4-46a6-87e1-30dc93191009 # PersonalÂ & Medical  Insurance
handle: personalMedicalInsurance
maxAuthors: 1
name: "Personal\_& Medical  Insurance"
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: pages/Personal-Medical-Insurance/index.twig
    uriFormat: Personal-Medical-Insurance
type: single
