defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b692872d-72dd-446b-9762-81992436c375 # podcasts
handle: podcastEpisodes
maxAuthors: 1
name: 'Podcast Episodes'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: podcast-episodes/_entry.twig
    uriFormat: 'podcast-episodes/{slug}'
type: channel
