defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6389e4d4-c725-4073-ba17-8aac55dc636c # Page Builder
handle: refinancingRefixing
maxAuthors: 1
name: 'Refinancing & Refixing'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: _boilerplate/_layouts/layout-service.twig
    uriFormat: refinancing-refixing
type: single
