defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d71d9025-4b25-42b3-956c-faa7e975d728 # Page Builder2
handle: retirementPlanning
maxAuthors: 1
name: 'Retirement Planning'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: _boilerplate/_layouts/layout-service-2.twig
    uriFormat: retirement-planning
type: single
