defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: dd0c598b-fc22-4c8d-9255-b3c858be4247 # Savings and Investment Page
handle: savingsAndInvestmentPage
maxAuthors: 1
name: 'Savings and Investment Page'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: savings-and-investment-page/_entry.twig
    uriFormat: savings-and-investment-page
type: single
