defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fe20e1d7-e0c5-4e62-80f5-8fc24cea698d # Client Testimonial
handle: testimonials
maxAuthors: 1
name: Testimonials
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 1821eadd-897b-4595-8a33-fa93b664966c
type: structure
