defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 60ac3db5-de5e-4810-a0b1-4743170e9b60 # Timeline
handle: timeline
maxAuthors: 1
name: Timeline
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  904beb73-9861-43f3-8de7-90464f6457de: # foxplan
    enabledByDefault: true
    hasUrls: true
    template: timeline/_entry.twig
    uriFormat: 'timeline/{slug}'
structure:
  maxLevels: null
  uid: 315f4e8d-ece5-49b9-9ae5-ea7a2c844ddd
type: structure
